name: payments-test

on:
  pull_request:
    paths: 
      - 'payments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
      - run: cd payments && yarn && yarn run test:ci
      
